name: cnpj_company
description: Get data of companies by CNPJ

publish_to: "none"

version: 1.0.8+120

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  dio: ^4.0.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  mask_text_input_formatter: ^2.0.0
  snack: ^2.0.0
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  provider: ^5.0.0
  screenshot: ^1.2.3
  load: ^1.0.0

flutter_launcher_name:
  name: "CNPJ"

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  cider: ^0.1.0
  mockito: ^5.0.15
  build_runner: ^2.1.1
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter

cider:
  link_template:
    tag: https://github.com/wendreof/cnpj_company/releases/tag/%tag% # initial release link template
    diff: https://github.com/wendreof/cnpj_company/compare/%from%...%to% # subsequent releases link template

flutter_icons:
  image_path: "images/logo.jpeg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/logo.jpeg

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: Roboto Slab Bold
      fonts:
        - asset: fonts/RobotoSlab-Bold.ttf
    - family: Roboto Slab Light
      fonts:
        - asset: fonts/RobotoSlab-Light.ttf
